name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2025-10-03"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow"
database_id = "c3d654a3-de93-4507-99f0-d76f7ee0f2f4"
